// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJrF9Fv5bO1LHjk0a4d1UCdJCGSjpO3GA',
    appId: '1:473399528772:web:d22732aadd86547a9e9b11',
    messagingSenderId: '473399528772',
    projectId: 'nutralyse-ae55d',
    authDomain: 'nutralyse-ae55d.firebaseapp.com',
    storageBucket: 'nutralyse-ae55d.firebasestorage.app',
    measurementId: 'G-V4MQW04Z9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFbMrJ4X1kWXCbKEl7kgv_THE24SYAKXc',
    appId: '1:473399528772:android:3e8479fbff295b239e9b11',
    messagingSenderId: '473399528772',
    projectId: 'nutralyse-ae55d',
    storageBucket: 'nutralyse-ae55d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkymEc1BF11XImZTrpVAoBPSwaAq-JG-0',
    appId: '1:473399528772:ios:12e71bf72f4c3b1e9e9b11',
    messagingSenderId: '473399528772',
    projectId: 'nutralyse-ae55d',
    storageBucket: 'nutralyse-ae55d.firebasestorage.app',
    iosBundleId: 'com.example.nutralyseJd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkymEc1BF11XImZTrpVAoBPSwaAq-JG-0',
    appId: '1:473399528772:ios:12e71bf72f4c3b1e9e9b11',
    messagingSenderId: '473399528772',
    projectId: 'nutralyse-ae55d',
    storageBucket: 'nutralyse-ae55d.firebasestorage.app',
    iosBundleId: 'com.example.nutralyseJd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJrF9Fv5bO1LHjk0a4d1UCdJCGSjpO3GA',
    appId: '1:473399528772:web:fc5e08818e34f5f19e9b11',
    messagingSenderId: '473399528772',
    projectId: 'nutralyse-ae55d',
    authDomain: 'nutralyse-ae55d.firebaseapp.com',
    storageBucket: 'nutralyse-ae55d.firebasestorage.app',
    measurementId: 'G-7EYEQNXDLY',
  );
}
